# Image tags for GitOps - ArgoCD watches these values - testing
image:
  frontend:
    repository: urchytech/3-tier-deployment_frontend
    tag: 2717389b82ff6d0c845cb45e5b866336a548e914
  backend:
    repository: urchytech/3-tier-deployment_backend
    tag: 2717389b82ff6d0c845cb45e5b866336a548e914
