# Image tags for GitOps - ArgoCD watches these values - testing
image:
  frontend:
    repository: myk8sacr1.azurecr.io/client
    tag: latest
  backend:
    repository: myk8sacr1.azurecr.io/api
    tag: latest
